/*
 * Sponsored License - for use in support of a program or activity
 * sponsored by MathWorks.  Not for government, commercial or other
 * non-sponsored organizational use.
 *
 * redHSVmask1.c
 *
 * Code generation for function 'redHSVmask1'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "redHSVmask1.h"
#include "rgb2hsv.h"
#include "redHSVmask1_data.h"

/* Function Definitions */
void redHSVmask1(redHSVmask1StackData *SD, const emlrtStack *sp, const uint8_T
                 RGB[921600], boolean_T BW[307200])
{
  int32_T i0;
  int32_T i1;
  (void)sp;
  covrtLogFcn(&emlrtCoverageInstance, 0U, 0U);
  covrtLogBasicBlock(&emlrtCoverageInstance, 0U, 0U);

  /* createMask  Threshold RGB image using auto-generated code from colorThresholder app. */
  /*   [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using */
  /*   auto-generated code from the colorThresholder App. The colorspace and */
  /*   minimum/maximum values for each channel of the colorspace were set in the */
  /*   App and result in a binary mask BW and a composite image maskedRGBImage, */
  /*   which shows the original RGB image values under the mask BW. */
  /*  Auto-generated by colorThresholder app on 03-Nov-2016 */
  /* ------------------------------------------------------ */
  /*  Convert RGB image to chosen color space */
  rgb2hsv(RGB, SD->f0.I);

  /*  Define thresholds for channel 1 based on histogram settings */
  /*  Define thresholds for channel 2 based on histogram settings */
  /*  Define thresholds for channel 3 based on histogram settings */
  /*  Create mask based on chosen histogram thresholds */
  for (i0 = 0; i0 < 640; i0++) {
    for (i1 = 0; i1 < 480; i1++) {
      BW[i1 + 480 * i0] = (((SD->f0.I[i1 + 480 * i0] >= 0.951) || (SD->f0.I[i1 +
        480 * i0] <= 0.049)) && (SD->f0.I[307200 + (i1 + 480 * i0)] >= 0.451) &&
                           (SD->f0.I[307200 + (i1 + 480 * i0)] <= 1.0) &&
                           (SD->f0.I[614400 + (i1 + 480 * i0)] >= 0.0) &&
                           (SD->f0.I[614400 + (i1 + 480 * i0)] <= 1.0));
    }
  }

  /*  Initialize output masked image based on input image. */
  /*  Set background pixels where BW is false to zero. */
}

/* End of code generation (redHSVmask1.c) */
