% Auto-generated by stereoCalibrator app on 03-Nov-2016
%-------------------------------------------------------


% Define images to process
imageFileNames1 = {'C:\Users\Austin Musser\Pictures\Camera Roll\left\cam1.1.png',...
    'C:\Users\Austin Musser\Pictures\Camera Roll\left\cam1.2.png',...
    'C:\Users\Austin Musser\Pictures\Camera Roll\left\cam1.5.png',...
    };
imageFileNames2 = {'C:\Users\Austin Musser\Pictures\Camera Roll\new right\cam2.1.png',...
    'C:\Users\Austin Musser\Pictures\Camera Roll\new right\cam2.2.png',...
    'C:\Users\Austin Musser\Pictures\Camera Roll\new right\cam2.5.png',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames1, imageFileNames2);

% Generate world coordinates of the checkerboard keypoints
squareSize = 1;  % in units of 'in'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[stereoParams, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'in', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

% View reprojection errors
h1=figure; showReprojectionErrors(stereoParams);

% Visualize pattern locations
h2=figure; showExtrinsics(stereoParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, stereoParams);

% You can use the calibration data to rectify stereo images.
I1 = imread(imageFileNames1{1});
I2 = imread(imageFileNames2{1});
[J1, J2] = rectifyStereoImages(I1, I2, stereoParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('StereoCalibrationAndSceneReconstructionExample')
% showdemo('DepthEstimationFromStereoVideoExample')
